CREATE TABLE EMPLOYEE (E_ID NUMBER(10),E_NAME VARCHAR2(10),E_DEPT VARCHAR2(8),E_SALARY NUMBER (10));
ALTER TABLE E_ID MODIFY 'EMPLOYEE' ;
 SELECT * FROM EMPLOYEE
 
 
 update EMPLOYEE set e_DEPT='HR' WHERE E_ID='600';

  
 INSERT INTO EMPLOYEE VALUES (100,'RAM','HR',1000);
 INSERT INTO EMPLOYEE VALUES  (200,'RAM','HR',2000);
 INSERT INTO EMPLOYEE VALUES (300,'RAM','HR',4000);
 INSERT INTO EMPLOYEE VALUES (400,'RAM','HR',5000);
 INSERT INTO EMPLOYEE VALUES (500,'RAM','HR',6000);
 INSERT INTO EMPLOYEE VALUES (600,'R AM','HR',7000);
 INSERT INTO EMPLOYEE VALUES (700,'RAM','HR',8000);
 
 select * from E_ID
 
 update E_ID set eid_pk=eid ;
 
 CREATE TABLE PROJECT1 (PID_PK NUMBER(10)PRIMARY KEY,P_NAME VARCHAR2(8),LOCATION VARCHAR2(8));
 
 
 alter table PROJECt1 rename column pid_pk to pid; 
  ALTER TABLE e_id MODIFY SNUM_PK NUMBER(8) PRIMARY KEY; 
  
  alter table E_ID drop constant eid_pk;
 
SELECT * FROM PROJECT1
ALTER TABLE PROJECT1 ADD EID_FK NUMBER(10);
INSERT INTO PROJECT1 VALUES (121,'TOT','NEWYORK','100'); 
INSERT INTO PROJECT1 VALUES (131,'BIGDATA','NEWYORK','200'); 
INSERT INTO PROJECT1 VALUES (141,'RETAIL','LONDON','300'); 
INSERT INTO PROJECT1 VALUES (124,'ANDRIOD','PARIS','400'); 
INSERT INTO PROJECT1 VALUES (125,'TOT','NEWYORK','500');
INSERT INTO PROJECT1 VALUES (151,'BIGDATA','PARIS','600');
INSERT INTO PROJECT1 VALUES (128,'ANDRIOD','LONDON','700');
 
INSERT INTO PROJECT1 VALUES (171,'TOT','NEWYORK','100'); 
INSERT INTO PROJECT1 VALUES (125,'TOT','NEWYORK','100'); 


--SELECT MAX(E_SALARY)FROM EMPLOYEE 
 SELECT E_NAME FROM EMPLOYEE WHERE E_SALARY IN(SELECT MAX(E_SALARY) FROM EMPLOYEE GROUP BY E_DEPT);
   
 
 
 --JOIN TABLE 
   
 SELECT E_NAME,E_DEPT,p_name FROM EMPLOYEE,PROJECT1 WHERE EMPLOYEE.E_iD>PROJECT1.PID;
  SELECT E_NAME,E_DEPT,p_name FROM employee natural join project1;
--three are same equi, natural join and natural

 --inner
  SELECT E_NAME,E_DEPT,p_name FROM EMPLOYEE inner join PROJECT1 on EMPLOYEE.E_iD>PROJECT1.PID;
 -- cross join
   SELECT E_NAME,E_DEPT,p_name FROM EMPLOYEE cross join PROJECT1;
--  outer join
   SELECT E_NAME,E_DEPT,p_name FROM EMPLOYEE left outer join PROJECT1 on (EMPLOYEE.E_iD<>PROJECT1.PID);
   SELECT E_NAME,E_DEPT,p_name FROM EMPLOYEE right outer join PROJECT1 on (EMPLOYEE.E_iD<>PROJECT1.PID);
`
